### PR TITLE
Updated to Webpack 4, and made sure it runs

### PR DESCRIPTION
**Pull request by lemeb**
Changes: 

- Update to Webpack 4 / Babel 7
- Had to change `babelrc` because `presets` have changed and `env.build.optional` is deprecated.
- `ExtractTextPlugin` and `uglifyJsPlugin` are deprecated, I replaced them with other mechanisms that **may not work**.

### CODE REVIEW

**Comment by atmoio** [comment]
@lemeb why did you close this?

**Comment by lemeb** [comment]
I did the fork by mistake into the `sn-extensions:master` branch instead of `lemeb:master` branch. The thing is that I'm not completely sure that all the changes I made do not create any regressions. But I'm happy to re-open the pull so you can look at it and check that everything is OK.

**Comment by lemeb** [comment]
@mobitar Ok! You have it at #3 now, with much more notes about what may/may not work.

Have a great day, and thank you so much for all your work! Happy, SN subscriber here who is very much hoping SN stays around for a while indeed.

**Comment by atmoio** [comment]
Ok great, thanks! And happy to hear that 🙏

**Pull request closed without merging**
